/**
 * Generate docs/catalog-state.md — every current-state number about the
 * catalog, read from the live database.
 *
 * WHY THIS EXISTS. Current-state numbers were being typed into prose, in four
 * places that had no way to notice each other going stale. On 2026-07-28 three
 * of them disagreed at once:
 *
 *   · the Notion runbook said cottage tagged 533 of 595 plants; the re-tag pass
 *     had taken it to ~290 the day before
 *   · the Notion runbook said the guard-stamp backfill was "deliberately not
 *     done"; architecture.md said it had been done, three hours earlier
 *   · a memory note said the scope-check branch was unpushed; it was merged
 *
 * None of those was carelessness. A number written into a sentence has no way
 * to know the world moved. So current-state numbers now live in ONE generated
 * file, and prose links to it instead of restating it.
 *
 * WHAT BELONGS HERE vs IN PROSE. This file carries only what is true RIGHT NOW
 * and knowable from a query. Historical facts — "round 8 seeded 101 species",
 * "cottage ran at 89.6% before the re-tag" — are events, not state: they stay
 * in docs/database-log.md and never go stale.
 *
 * NO TIMESTAMP, DELIBERATELY. A generated-at line would change on every run and
 * make the file diff against itself, which would defeat the point: with no
 * timestamp, `catalog-state.ts && git diff --exit-code docs/catalog-state.md`
 * is a real staleness check. Git's own commit date is the freshness record.
 *
 * Read-only, no AI calls.
 *
 *   ./node_modules/.bin/tsx --env-file=.env.local scripts/catalog-state.ts
 */

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { getSupabaseAdmin } from '../lib/supabase-admin'
import { fetchAllRows } from '../lib/paginate'
import { STEP_DEFS } from './round-status'

const OUT = join(process.cwd(), '..', '..', 'docs', 'catalog-state.md')

interface Row {
  id: string
  is_curated: boolean | null
  style_tags: string[] | null
  seasonal_care: unknown
  hardiness_rating: string | null
  hardiness_verified: boolean | null
  native_region: string[] | null
  image_url: string | null
  image_url_curated: string | null
  is_greenery: boolean | null
  ai_drafted_at: string | null
  botanical_checked_at: string | null
  native_checked_at: string | null
  native_region_checked_at: string | null
  style_checked_at: string | null
  greenery_checked_at: string | null
  image_checked_at: string | null
  editorial_checked_at: string | null
}

const pct = (n: number, total: number) =>
  total === 0 ? '—' : `${((n / total) * 100).toFixed(1)}%`

async function main() {
  const db = getSupabaseAdmin()

  const plants = await fetchAllRows<Row>((from, to) =>
    db.from('plants').select('*').order('id').range(from, to)
  )
  const combos = await fetchAllRows<{ id: string }>((from, to) =>
    db.from('plant_combinations').select('id').order('id').range(from, to)
  )

  const total = plants.length
  const count = (f: (p: Row) => boolean) => plants.filter(f).length

  // Tag distribution — the number that went stale in Notion.
  const tagCounts = new Map<string, number>()
  for (const p of plants) {
    for (const t of p.style_tags ?? []) {
      tagCounts.set(t, (tagCounts.get(t) ?? 0) + 1)
    }
  }
  const tags = [...tagCounts.entries()].sort((a, b) => b[1] - a[1])

  // Step coverage comes from the STEP_DEFS registry, not a second list here —
  // adding a pipeline step updates this table automatically.
  const stampSteps = STEP_DEFS.filter((d) => d.stampColumn)

  const L: string[] = []
  L.push(
    '<!-- GENERATED by apps/web/scripts/catalog-state.ts — DO NOT EDIT -->'
  )
  L.push('')
  L.push('# Catalog state')
  L.push('')
  L.push(
    'Every current-state number about the catalog, read from the live database.'
  )
  L.push('')
  L.push(
    '**Do not edit this file, and do not copy these numbers into prose.** Link here'
  )
  L.push(
    'instead. Numbers written into sentences have no way to notice the world moved,'
  )
  L.push(
    'which is how three documents came to disagree about the catalog on 2026-07-28.'
  )
  L.push('')
  L.push('Regenerate, and check nothing has drifted:')
  L.push('')
  L.push('```')
  L.push(
    './node_modules/.bin/tsx --env-file=.env.local scripts/catalog-state.ts'
  )
  L.push('git diff --exit-code docs/catalog-state.md')
  L.push('```')
  L.push('')
  L.push(
    'There is no generated-at line on purpose: without one, the file only changes'
  )
  L.push(
    "when the data changes, so that diff is a real staleness check. Git's commit"
  )
  L.push('date is the freshness record.')
  L.push('')
  L.push('## Size')
  L.push('')
  L.push('| | |')
  L.push('| --- | ---: |')
  L.push(`| species | ${total} |`)
  L.push(`| companion pairs | ${combos.length} |`)
  L.push('')
  L.push('## Pipeline coverage')
  L.push('')
  L.push(
    'One row per step that stamps a column, from the `STEP_DEFS` registry in'
  )
  L.push(
    '`apps/web/scripts/round-status.ts`. A step added there appears here automatically.'
  )
  L.push('')
  L.push('| step | column | judged | share |')
  L.push('| --- | --- | ---: | ---: |')
  for (const def of stampSteps) {
    const col = def.stampColumn as keyof Row
    const n = count((p) => p[col] != null)
    L.push(
      `| \`${def.step}\` | \`${def.stampColumn}\` | ${n} / ${total} | ${pct(n, total)} |`
    )
  }
  L.push('')
  L.push('## Field coverage')
  L.push('')
  L.push('| field | state | count |')
  L.push('| --- | --- | ---: |')
  L.push(`| \`ai_drafted_at\` | drafted | ${count((p) => !!p.ai_drafted_at)} |`)
  L.push(
    `| \`is_curated\` | editorially reviewed | ${count((p) => p.is_curated === true)} |`
  )
  // Split on the STAMP, never the value: style_tags is NOT NULL DEFAULT '{}'
  // so `=== null` is unreachable (trap 26) — the old NULL row here printed 0
  // in all 16 committed versions while 100 unjudged rows sat in the neutral
  // row above it, dressed as verdicts.
  L.push(
    `| \`style_tags\` | style-neutral (stamped, \`[]\` — a valid judgment) | ${count((p) => p.style_checked_at != null && Array.isArray(p.style_tags) && p.style_tags.length === 0)} |`
  )
  L.push(
    `| \`style_tags\` | never judged (\`style_checked_at\` NULL — a gap) | ${count((p) => p.style_checked_at == null)} |`
  )
  L.push(
    `| \`seasonal_care\` | null | ${count((p) => p.seasonal_care == null)} |`
  )
  L.push(
    `| \`native_region\` | empty | ${count((p) => !p.native_region || p.native_region.length === 0)} |`
  )
  L.push(`| \`is_greenery\` | true | ${count((p) => p.is_greenery === true)} |`)
  L.push(
    `| \`hardiness_rating\` | drafted | ${count((p) => !!p.hardiness_rating)} |`
  )
  L.push(
    `| \`hardiness_verified\` | human-verified | ${count((p) => p.hardiness_verified === true)} |`
  )
  L.push(
    `| images | no image at all | ${count((p) => !p.image_url && !p.image_url_curated)} |`
  )
  L.push(
    `| images | have an editorial pick (\`image_url_curated\`) | ${count((p) => !!p.image_url_curated)} |`
  )
  L.push('')
  L.push('## Style tag distribution')
  L.push('')
  L.push(
    'A tag on much more than 40% of the catalog cannot discriminate, which is what'
  )
  L.push(
    'made the style filter a no-op before the 2026-07-28 re-tag. `curate-styles.ts`'
  )
  L.push('warns above that bar on every full run.')
  L.push('')
  L.push('| tag | plants | share |')
  L.push('| --- | ---: | ---: |')
  for (const [tag, n] of tags) {
    L.push(`| ${tag} | ${n} | ${pct(n, total)} |`)
  }
  L.push('')

  writeFileSync(OUT, L.join('\n'))
  console.log(`Wrote ${OUT}`)
  console.log(`${total} species, ${combos.length} pairs.`)
}

main().catch((err) => {
  console.error('Unexpected error:', err)
  process.exit(1)
})
