/**
 * Render `docs/round-runbook.md` from the RUNBOOK array.
 *
 * WHY GENERATED. The order of a round has lived in prose (`architecture.md`
 * §25, the Notion runbook, handoff notes) and in code, and the prose is what
 * went wrong: the seasonal-care step was missing from the written runbook
 * entirely, so every plant seeded after Care Tips v2 shipped had no care tip.
 * Nobody noticed for weeks, because the document looked complete.
 *
 * So the page is derived, like `catalog-state.md` and the token consumers
 * list. Nothing about the order can be typed by a person, which means it
 * cannot be typed wrongly. What a person still writes is the part a machine
 * cannot know: why a step exists, and what bit us. That lives in the step's
 * own source comments and in `database-log.md`.
 *
 * `pnpm runbook:check` fails when the page is out of date, which is the whole
 * point — a generated file nobody regenerates is just a stale file with extra
 * steps.
 *
 * Usage (from apps/web):
 *   pnpm runbook          # write the page
 *   pnpm runbook:check    # fail if it is stale
 */

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { RUNBOOK, type Step } from './runbook'

const OUT = join(process.cwd(), '..', '..', 'docs', 'round-runbook.md')

const work = RUNBOOK.filter((s) => !s.alwaysRun)
const bookends = RUNBOOK.filter((s) => s.alwaysRun)

function command(s: Step): string {
  const args = ['--round <label>', ...(s.args ?? [])].join(' ')
  return `scripts/${s.script} ${args}`
}

function row(s: Step): string {
  return `| ${s.runbook} | \`${s.step}\` | \`${command(s)}\` |`
}

const page = `# The round runbook

<!-- GENERATED by apps/web/scripts/generate-runbook-doc.ts — do not edit.
     The order lives in apps/web/scripts/runbook.ts and nowhere else.
     Regenerate with \`pnpm runbook\`; \`pnpm runbook:check\` fails if stale. -->

A round is one batch of plants taken from seeded to signed off. This page is
the whole process. It is generated from the array \`run-round.ts\` executes, so
it cannot describe a different order than the one that runs.

## Run it

\`\`\`bash
pnpm round:run --round <label> --dry-run   # the plan, costs nothing
pnpm round:run --round <label>             # run it
pnpm round:progress --round <label>        # what is outstanding
\`\`\`

Steps are detected as done from database state, so an interrupted run is
restarted with the same command and pays for nothing twice. A step that fails
STOPS the run. Nothing retries, skips ahead, or works around a failure.

## What it will not do

**It does not seed.** Seeding is where a round's judgment lives — which
species, chosen against which measured gap — and it is a different script each
time. Run the seed first; the runner picks up from a round that exists.

**It does not decide anything a person should.** Held rows, waivers and
editorial verdicts are recorded, not resolved.

## The ${work.length} steps

${['| # | step | command |', '| --- | --- | --- |', ...work.map(row)].join('\n')}

## The ${bookends.length} book-ends

These run whether or not the round has work, because they are free and
skipping one on a bad guess is not.

${['| # | step | command |', '| --- | --- | --- |', ...bookends.map(row)].join('\n')}

${bookends
  .filter((s) => s.onFail)
  .map((s) => `**If \`${s.step}\` fails.** ${s.onFail}`)
  .join('\n\n')}

## Not in the per-round cadence

\`curate-styles\` and \`curate-greenery\` are repair passes for older data —
\`curate-plants\` already does both jobs for a new seed, from the same shared
definitions. \`draft-hardiness\` feeds a parked feature (§27). All three stay
registered in \`STEP_DEFS\` so their stamp columns are still claimed; they are
simply not run every round.

## When the round is done

\`log-db-session.ts --round <label>\` writes the factual half of the
\`database-log.md\` entry. The half about what bit you is the half that matters,
and it is yours.

A finished round is **frozen**: every step refuses to write outside its scope,
and reaching an older round's rows takes an explicit \`--all --why "<reason>"\`.
`

writeFileSync(OUT, page)
console.log(
  `Wrote ${OUT} — ${work.length} steps, ${bookends.length} book-ends.`
)
