/**
 * Trap 3's live half, pinned: --apply replays reports/native-region-regen.json,
 * a gitignored file of unknown age. Until 2026-08-14 it did so with no scope
 * check at all, so a stale --all plan replayed after a seed would rewrite the
 * whole catalog while every message on screen said "round N" — the shape that
 * changed 20 settled rows in round 8. assertPlanScope is the refusal.
 */
import { describe, expect, it } from 'vitest'

import { assertPlanScope, planRowIsStale } from './regenerate-native-region'

describe('assertPlanScope: --apply refuses a plan its scope did not generate', () => {
  it('a plan from --all replayed under --round throws', () => {
    expect(() =>
      assertPlanScope({ kind: 'all' }, { kind: 'round', label: '11' })
    ).toThrow(/does not match/)
  })

  it('a plan from another round throws', () => {
    expect(() =>
      assertPlanScope(
        { kind: 'round', label: '8' },
        { kind: 'round', label: '11' }
      )
    ).toThrow(/does not match/)
  })

  it('a plan with no recorded scope is refused, not trusted', () => {
    // The legacy format wrote { generatedAt: null, plan } — indistinguishable
    // from a stale --all sweep, so it must never be applied as-is.
    expect(() =>
      assertPlanScope(undefined, { kind: 'round', label: '11' })
    ).toThrow(/records no scope/)
    expect(() => assertPlanScope(null, { kind: 'round', label: '11' })).toThrow(
      /records no scope/
    )
    expect(() =>
      assertPlanScope({ kind: 'sideways' }, { kind: 'round', label: '11' })
    ).toThrow(/records no scope/)
  })

  it('the matching scope passes', () => {
    expect(() =>
      assertPlanScope(
        { kind: 'round', label: '11' },
        { kind: 'round', label: '11' }
      )
    ).not.toThrow()
    expect(() =>
      assertPlanScope({ kind: 'all' }, { kind: 'all' })
    ).not.toThrow()
  })

  it('--ids plans match on the set, not the order', () => {
    expect(() =>
      assertPlanScope(
        { kind: 'ids', ids: ['b', 'a'] },
        { kind: 'ids', ids: ['a', 'b'] }
      )
    ).not.toThrow()
    expect(() =>
      assertPlanScope(
        { kind: 'ids', ids: ['a'] },
        { kind: 'ids', ids: ['a', 'b'] }
      )
    ).toThrow(/does not match/)
  })
})

/**
 * The other half of trap 3, which assertPlanScope does not reach: a plan can be
 * generated by the right scope and still be applied to state that moved
 * underneath it. The plan is reviewed by a person and applied later, and a hand
 * correction landing in between is silently re-derived away — the clobbering
 * that MANUAL_OVERRIDES was built to patch one plant at a time.
 *
 * Fails against the pre-2026-08-16 code, which had no per-row comparison at all:
 * every planned row was written unconditionally.
 */
describe('planRowIsStale: --apply refuses a row that moved since the plan', () => {
  it('a row still holding what the plan saw is applied', () => {
    expect(
      planRowIsStale(['Southeastern Europe'], ['Southeastern Europe'])
    ).toBe(false)
  })

  it('a row corrected by hand since the plan is stale', () => {
    // THE case: the plan was built from ['Australia'], somebody removed it after
    // reviewing the evidence, and replaying the plan would put it back.
    expect(planRowIsStale([], ['Australia'])).toBe(true)
  })

  it('order and duplicates are not drift', () => {
    // The two sides come from different places — a JSON plan file and PostgREST
    // — so a comparison sensitive to order would call every row stale and the
    // guard would refuse everything, which is how a guard gets switched off.
    expect(planRowIsStale(['b', 'a'], ['a', 'b'])).toBe(false)
    expect(planRowIsStale(['a', 'a', 'b'], ['b', 'a'])).toBe(false)
  })

  it('null and empty are the same absence', () => {
    // native_region is nullable, and a row that never had tags reads back null
    // from PostgREST while the plan records []. Treating those as different
    // would make every untagged row permanently unappliable.
    expect(planRowIsStale(null, [])).toBe(false)
    expect(planRowIsStale(null, ['Australia'])).toBe(true)
  })
})
