// GENERATED by apps/web/scripts/catalog-state.ts — do not edit.
// Run `pnpm catalog:state` to regenerate; `pnpm catalog:state:check` fails when stale.
//
// Plants currently holding each style. Drives which styles the Explore filter
// offers (see STYLE_OPTIONS in lib/explore-filters.ts) — the vocabulary itself
// is lib/style-tags.ts and is deliberately larger than this.

import type { StyleTag } from './style-tags'

export const stylePlantCounts: Record<StyleTag, number> = {
  cottage: 215,
  mediterranean: 132,
  wildflower: 45,
  modern: 61,
  lush: 48,
  classic: 42,
  japanese: 63,
  chinese: 48,
  tropical: 18,
  desert: 24,
  herb: 84,
  pollinator: 140,
  cutting: 44,
  sensory: 62,
  woodland: 165,
  moon: 14,
  gothic: 10,
  prairie: 73,
  winter: 64,
}
