// GENERATED by apps/web/scripts/catalog-state.ts — do not edit.
// Run `pnpm catalog:state` to regenerate; `pnpm catalog:state:check` fails when stale.
//
// Plants currently holding each style. Drives which styles the Explore filter
// offers (see STYLE_OPTIONS in lib/explore-filters.ts) — the vocabulary itself
// is lib/style-tags.ts and is deliberately larger than this.

import type { StyleTag } from './style-tags'

export const stylePlantCounts: Record<StyleTag, number> = {
  cottage: 363,
  mediterranean: 195,
  wildflower: 131,
  modern: 115,
  lush: 118,
  classic: 120,
  japanese: 0,
  chinese: 1,
  provence: 0,
  tropical: 0,
  desert: 0,
  herb: 0,
  pollinator: 0,
  cutting: 0,
  sensory: 0,
  woodland: 0,
  moon: 0,
  gothic: 0,
  prairie: 0,
  winter: 0,
}
