// GENERATED by apps/web/scripts/catalog-state.ts — do not edit.
// Run `pnpm catalog:state` to regenerate; `pnpm catalog:state:check` fails when stale.
//
// Plants currently holding each style. Drives which styles the Explore filter
// offers (see STYLE_OPTIONS in lib/explore-filters.ts) — the vocabulary itself
// is lib/style-tags.ts and is deliberately larger than this.

import type { StyleTag } from './style-tags'

export const stylePlantCounts: Record<StyleTag, number> = {
  cottage: 216,
  mediterranean: 131,
  wildflower: 45,
  modern: 62,
  lush: 49,
  classic: 50,
  japanese: 81,
  chinese: 60,
  tropical: 19,
  desert: 24,
  herb: 84,
  pollinator: 140,
  cutting: 45,
  sensory: 65,
  woodland: 166,
  moon: 14,
  gothic: 10,
  prairie: 73,
  winter: 65,
}
