-- Diary photos go private. The public posture from the original diary
-- migration was explicitly temporary ("revisit once real auth/profiles
-- exist" — architecture.md §18); real auth shipped (§24), so this is that
-- revisit. Beyond flipping the bucket, the old policies had no role or
-- ownership restriction at all, which let anyone holding the anon key list,
-- upload into, and delete from the bucket via the storage API directly.
--
-- Ownership keys on the path convention {gardenId}/{plantId}/{timestamp}-
-- {filename}: the first folder is the owning garden. Reads in the app now go
-- through signed URLs generated by the session client (server/diary-actions
-- .ts), which requires passing the select policy below. See §28.

update storage.buckets set public = false where id = 'diary-photos';

drop policy if exists "Anyone can view diary photos" on storage.objects;
drop policy if exists "Users can upload their own diary photos" on storage.objects;
drop policy if exists "Users can delete their own diary photos" on storage.objects;

create policy "Users can view own garden diary photos"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'diary-photos'
    and exists (
      select 1 from public.gardens
      where gardens.id::text = (storage.foldername(name))[1]
        and gardens.user_id = auth.uid()
    )
  );

create policy "Users can upload own garden diary photos"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'diary-photos'
    and exists (
      select 1 from public.gardens
      where gardens.id::text = (storage.foldername(name))[1]
        and gardens.user_id = auth.uid()
    )
  );

create policy "Users can delete own garden diary photos"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'diary-photos'
    and exists (
      select 1 from public.gardens
      where gardens.id::text = (storage.foldername(name))[1]
        and gardens.user_id = auth.uid()
    )
  );
